// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD60C_q4pAZxxL_c3SwuYH8FOJ3iFXmztM',
    appId: '1:144878556616:web:af7869860ab5042736dcfd',
    messagingSenderId: '144878556616',
    projectId: 'mail-359523',
    authDomain: 'mail-359523.firebaseapp.com',
    storageBucket: 'mail-359523.appspot.com',
    measurementId: 'G-4FHZCQG1ZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtIPlIY-L_GX2LJJDdVefxVg8SHPFOimo',
    appId: '1:144878556616:android:d02bfa2f2edc83fa36dcfd',
    messagingSenderId: '144878556616',
    projectId: 'mail-359523',
    storageBucket: 'mail-359523.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeVjq7BN0BWk0oIgia4_bRgQaSripJWjc',
    appId: '1:144878556616:ios:31c9d156d656cfb636dcfd',
    messagingSenderId: '144878556616',
    projectId: 'mail-359523',
    storageBucket: 'mail-359523.appspot.com',
    androidClientId: '144878556616-g80k131catl246a40ejeuastce4tal5e.apps.googleusercontent.com',
    iosClientId: '144878556616-6qov4sjuvl5bn1nq2unha10ni692mf6k.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasePicturesSaved',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeVjq7BN0BWk0oIgia4_bRgQaSripJWjc',
    appId: '1:144878556616:ios:31c9d156d656cfb636dcfd',
    messagingSenderId: '144878556616',
    projectId: 'mail-359523',
    storageBucket: 'mail-359523.appspot.com',
    androidClientId: '144878556616-g80k131catl246a40ejeuastce4tal5e.apps.googleusercontent.com',
    iosClientId: '144878556616-6qov4sjuvl5bn1nq2unha10ni692mf6k.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasePicturesSaved',
  );
}
